name: Deploy TodoApp to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Navigate to the existing repo or clone if missing
            cd ~/todoapp-devops || git clone https://github.com/aman7433/todoapp-devops.git ~/todoapp-devops
            cd ~/todoapp-devops
            git pull origin main

            # Ensure Docker is installed and running
            sudo systemctl start docker || true

            # Stop and remove any existing container
            docker stop todoapp || true
            docker rm todoapp || true

            # Build the Docker image with a proper tag
            docker build -t todoapp .

            # Run the container
            docker run -d -p 8000:8000 --name todoapp todoapp

            # Show running containers
            docker ps
